const voiceCommands = [
   new tizen.VoiceControlCommand("Test"),
   new tizen.VoiceControlCommand("Avatar"),
   new tizen.VoiceControlCommand("Matrix"),
   new tizen.VoiceControlCommand("Legion"),
   new tizen.VoiceControlCommand("Arrival"),
   new tizen.VoiceControlCommand("Gravity"),
   new tizen.VoiceControlCommand("Test play"),
   new tizen.VoiceControlCommand("Avatar play"),
   new tizen.VoiceControlCommand("Matrix play"),
   new tizen.VoiceControlCommand("Legion play"),
   new tizen.VoiceControlCommand("Arrival play"),
   new tizen.VoiceControlCommand("Gravity play"),
   new tizen.VoiceControlCommand("Catalog"),
   new tizen.VoiceControlCommand("List"),
   new tizen.VoiceControlCommand("Play Avatar"),
   new tizen.VoiceControlCommand("Play Matrix"),
   new tizen.VoiceControlCommand("Play Legion"),
   new tizen.VoiceControlCommand("Play Arrival"),
   new tizen.VoiceControlCommand("Play Gravity"),
 ];
